development:
  adapter: postgresql
  encoding: unicode
  database: atxmas_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: atxmas_test
  pool: 5
  username: postgres
  password:
